import type {
  CarrierRow,
  OrderWithPlan,
  PlanWithCarrier,
} from "@/lib/types/database"

const now = "2026-04-04T10:00:00.000Z"

export const demoCarriers: CarrierRow[] = [
  {
    id: "carrier-att",
    name: "AT&T",
    slug: "att",
    logo_url: null,
    description: "Nationwide prepaid eSIM coverage.",
    sort_order: 1,
    created_at: now,
  },
  {
    id: "carrier-tmobile",
    name: "T-Mobile",
    slug: "t-mobile",
    logo_url: null,
    description: "Fast setup with strong 5G coverage.",
    sort_order: 2,
    created_at: now,
  },
]

export const demoPlans: PlanWithCarrier[] = [
  {
    id: "plan-att-10gb",
    carrier_id: "carrier-att",
    name: "10GB Monthly",
    data_label: "10 GB",
    validity_days: 30,
    price_cents: 2900,
    currency: "NGN",
    features: ["5G", "Hotspot"],
    badge: "Best seller",
    is_featured: true,
    is_active: true,
    archived_at: null,
    created_at: now,
    carrier: {
      id: "carrier-att",
      name: "AT&T",
      slug: "att",
      logo_url: null,
    },
  },
  {
    id: "plan-tmobile-unlimited",
    carrier_id: "carrier-tmobile",
    name: "Unlimited Plus",
    data_label: "Unlimited",
    validity_days: 30,
    price_cents: 4900,
    currency: "NGN",
    features: ["5G", "Unlimited data", "Priority support"],
    badge: "Premium",
    is_featured: true,
    is_active: true,
    archived_at: null,
    created_at: now,
    carrier: {
      id: "carrier-tmobile",
      name: "T-Mobile",
      slug: "t-mobile",
      logo_url: null,
    },
  },
]

export const demoOrders: OrderWithPlan[] = [
  {
    id: "order-001",
    user_id: "user-demo-1",
    plan_id: "plan-att-10gb",
    status: "pending",
    full_name: "Jamie Carter",
    state: "Texas",
    phone_model: "iPhone 14 Pro",
    zip_code: "73301",
    imei: "356789012345678",
    email: "jamie@example.com",
    payment_reference: "TSK-20260402-A1B2",
    payment_receipt_path: null,
    imei_screenshot_path: null,
    delivery_proof_path: null,
    created_at: "2026-04-02T09:30:00.000Z",
    updated_at: "2026-04-02T09:30:00.000Z",
    plan: {
      id: "plan-att-10gb",
      carrier_id: "carrier-att",
      name: "10GB Monthly",
      data_label: "10 GB",
      validity_days: 30,
      price_cents: 2900,
      currency: "NGN",
      features: ["5G", "Hotspot"],
      badge: "Best seller",
      is_featured: true,
      is_active: true,
      archived_at: null,
      created_at: now,
      carrier: {
        name: "AT&T",
        slug: "att",
      },
    },
  },
  {
    id: "order-002",
    user_id: "user-demo-2",
    plan_id: "plan-tmobile-unlimited",
    status: "processing",
    full_name: "Morgan Lee",
    state: "California",
    phone_model: "Samsung Galaxy S24",
    zip_code: "90001",
    imei: "490154203237518",
    email: "morgan@example.com",
    payment_reference: "TSK-20260403-C3D4",
    payment_receipt_path: null,
    imei_screenshot_path: null,
    delivery_proof_path: null,
    created_at: "2026-04-03T14:15:00.000Z",
    updated_at: "2026-04-03T15:00:00.000Z",
    plan: {
      id: "plan-tmobile-unlimited",
      carrier_id: "carrier-tmobile",
      name: "Unlimited Plus",
      data_label: "Unlimited",
      validity_days: 30,
      price_cents: 4900,
      currency: "NGN",
      features: ["5G", "Unlimited data", "Priority support"],
      badge: "Premium",
      is_featured: true,
      is_active: true,
      archived_at: null,
      created_at: now,
      carrier: {
        name: "T-Mobile",
        slug: "t-mobile",
      },
    },
  },
  {
    id: "order-003",
    user_id: "user-demo-3",
    plan_id: "plan-att-10gb",
    status: "delivered",
    full_name: "Avery Johnson",
    state: "Florida",
    phone_model: "Google Pixel 8",
    zip_code: "33101",
    imei: "867530912345678",
    email: "avery@example.com",
    payment_reference: "TSK-20260401-E5F6",
    payment_receipt_path: null,
    imei_screenshot_path: null,
    delivery_proof_path: null,
    created_at: "2026-04-01T08:00:00.000Z",
    updated_at: "2026-04-01T10:45:00.000Z",
    plan: {
      id: "plan-att-10gb",
      carrier_id: "carrier-att",
      name: "10GB Monthly",
      data_label: "10 GB",
      validity_days: 30,
      price_cents: 2900,
      currency: "NGN",
      features: ["5G", "Hotspot"],
      badge: "Best seller",
      is_featured: true,
      is_active: true,
      archived_at: null,
      created_at: now,
      carrier: {
        name: "AT&T",
        slug: "att",
      },
    },
  },
]
